name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/olshevskiy87/goradiooooo

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/goradiooooo/go

    - name: Get dependencies
      run: make deps
      env:
        GOPATH: /home/runner/work/goradiooooo/go

    - name: Build
      run: make build_all
      env:
        GOPATH: /home/runner/work/goradiooooo/go

    - name: Test
      run: make lint
      env:
        GOPATH: /home/runner/work/goradiooooo/go
